version: '3.8'
services:
  postgres:
    image: postgres
    container_name: mypostgresdb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: apply_products_db
    ports:
      - "5432:5432"
    volumes:
      - mypostgresdbdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  mypostgresdbdata:
