version: '3.8'
services:
  postgres:
    image: postgres
    container_name: mypostgresdb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: apply_products_db
    ports:
      - "5432:5432"
    volumes:
      - myotherpostgresdbdata:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: .
      network: host
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      CONTENTFUL_SPACE_ID: ${CONTENTFUL_SPACE_ID}
      CONTENTFUL_ACCESS_TOKEN: ${CONTENTFUL_ACCESS_TOKEN}
      ENVIRONMENT: ${ENVIRONMENT}
      CONTENT_TYPE: ${CONTENT_TYPE}
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  myotherpostgresdbdata:
  # mypostgresdbdata:
